#! /bin/sh
# /etc/init.d/pressScanner
#

# Some things that run always
touch /opt/scanner/opt/scanner/activeScan.py

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting activeScan.py "
    python3 /opt/scanner/opt/scanneractiveScan.py
    ;;
  stop)
    echo "Stopping activeScan.py"
    ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop}"
    exit 1
    ;;
esac

exit 0
